[build]
  publish = "."
  functions = "netlify/functions"
  command = "npm install"

[[redirects]]
  from = "/api"
  to = "/.netlify/functions/api"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
