/**
 * src/ui/studio/InAppUsage.tsx — what the app actually asks of this component.
 *
 * The rest of the workbench shows what a component CAN do. This shows what is
 * really being asked of it: every call site in SIOMAC, deduped by prop
 * signature, rendered live with the real component.
 *
 * ⭐ Derived, never hand-maintained. The data comes from
 * `docs/generated/button-usage.json`, regenerated by `npm run repo:index` — so a
 * button added anywhere appears here without anyone updating a list. A
 * hand-written inventory is wrong the first time someone adds a button, which is
 * the same failure the component registry exists to prevent.
 *
 * ⭐ ONE prominent shape, the rest behind an expander. 41 distinct shapes shown
 * at once is a wall; the dominant one answers "what does a SIOMAC button look
 * like?" at a glance, and the tail is there when the question is "what else is
 * out there?".
 *
 * ⚠ Two honest counters, shown rather than hidden. Sites whose props are
 * expressions (`variant={tone}`) cannot be resolved statically and are counted,
 * not rendered — a rendered guess would be worse than an admitted gap. Legacy
 * `<button class="btn…">` markup is counted too: omitting it would make the page
 * read as though the app were fully migrated.
 */

import { type VNode } from 'preact';
import { useState } from 'preact/hooks';
import { defaultProps, type ComponentDef, type PropValues } from '../registry';
import usage from './generated/button-usage.json';

interface Shape {
  props: Record<string, string | boolean>;
  count: number;
  zones: Record<string, number>;
  files: string[];
}

/** Only Button has a generated inventory today; the shape is component-agnostic. */
const DATA: Record<string, { totals: Record<string, number>; shapes: Shape[] }> = {
  button: usage as unknown as { totals: Record<string, number>; shapes: Shape[] },
};

function describe(props: Record<string, string | boolean>): string {
  const parts = Object.entries(props).map(([k, v]) => (v === true ? k : `${k}=${String(v)}`));
  return parts.length > 0 ? parts.join(' · ') : 'defaults';
}

function ShapeCard({ def, shape, primary, checked, onToggle }: {
  def: ComponentDef; shape: Shape; primary?: boolean;
  checked: boolean; onToggle: () => void;
}): VNode {
  const props: PropValues = { ...defaultProps(def), ...(shape.props as PropValues) };
  const zones = Object.entries(shape.zones)
    .sort((a, b) => b[1] - a[1])
    .map(([z, n]) => `${n} ${z}`)
    .join(' · ');
  const sig = describe(shape.props);

  return (
    <article class={`sds-use__card${primary ? ' sds-use__card--primary' : ''}`}>
      <input type="checkbox" class="sds-use__check" checked={checked}
        aria-label={`Select ${sig}`} onChange={onToggle} />
      <div class="sds-use__spec">{def.render ? def.render(props, 'default') : null}</div>
      <div class="sds-use__meta">
        <code>{sig}</code>
        <span>{shape.count} {shape.count === 1 ? 'site' : 'sites'} · {zones}</span>
      </div>
    </article>
  );
}

export function InAppUsage({ def }: { def: ComponentDef }): VNode | null {
  const [expanded, setExpanded] = useState(false);
  const [selected, setSelected] = useState<Set<string>>(() => new Set());
  const [status, setStatus] = useState<'idle' | 'copied' | 'failed'>('idle');
  const data = DATA[def.id];
  if (!data || !def.render) return null;

  const [first, ...rest] = data.shapes;
  if (!first) return null;

  const toggle = (sig: string): void => setSelected(prev => {
    const next = new Set(prev);
    if (next.has(sig)) next.delete(sig); else next.add(sig);
    return next;
  });

  /**
   * Copy the selection as text that is actually actionable — the prop signature,
   * the site count and the files. A list of shape names alone would just start
   * another round of "which ones, where?".
   */
  const copySelection = (): void => {
    const lines = data.shapes
      .filter(s => selected.has(describe(s.props)))
      .map(s => [
        `- ${describe(s.props)}  (${s.count} sites)`,
        ...s.files.map(f => `    ${f}`),
      ].join('\n'));
    const text = `${def.name} shapes to remove (${lines.length}):\n\n${lines.join('\n')}`;

    /* The Clipboard API rejects without a user gesture, in an insecure context,
       or when the document is unfocused. Both outcomes are reported: handling
       only the success path made a failed copy look identical to a successful
       one — button unchanged, clipboard empty, user none the wiser.

       No execCommand fallback: it is deprecated and the linter rightly refuses
       it. The app is served over localhost/https where the modern API works, so
       the honest trade is to fail visibly rather than carry dead legacy. */
    const settle = (ok: boolean): void => {
      setStatus(ok ? 'copied' : 'failed');
      setTimeout(() => setStatus('idle'), 2200);
    };
    navigator.clipboard.writeText(text).then(() => settle(true), () => settle(false));
  };

  return (
    <section class="sds-ov__sec">
      <div class="sds-ov__hd">
        <h4>In the app</h4>
        <p>
          {data.totals.canonicalSites} canonical call sites across SIOMAC, deduped to{' '}
          {data.totals.distinctShapes} distinct shapes. Generated — a button added anywhere
          appears here after the next <code>repo:index</code>.
        </p>
      </div>

      <div class="sds-ov__surface">
        <ShapeCard def={def} shape={first} primary
          checked={selected.has(describe(first.props))}
          onToggle={() => toggle(describe(first.props))} />

        {rest.length > 0 && (
          <>
            <button type="button" class="sds-use__more"
              aria-expanded={expanded}
              onClick={() => setExpanded(v => !v)}>
              {expanded ? `Hide ${rest.length} other shapes` : `Show ${rest.length} other shapes`}
            </button>
            {expanded && (
              <div class="sds-use__grid">
                {rest.map(s => (
                  <ShapeCard def={def} shape={s} key={describe(s.props)}
                    checked={selected.has(describe(s.props))}
                    onToggle={() => toggle(describe(s.props))} />
                ))}
              </div>
            )}
          </>
        )}

        {/* Selection toolbar — pick the shapes to retire, copy them out as
            something actionable rather than a screenshot of a list. */}
        <div class="sds-use__bar">
          <button type="button" class="sds-use__act"
            onClick={() => setSelected(new Set(data.shapes.map(s => describe(s.props))))}>
            Select all {data.shapes.length}
          </button>
          <button type="button" class="sds-use__act"
            disabled={selected.size === 0}
            onClick={() => setSelected(new Set())}>Clear</button>
          <span class="sds-use__count">{selected.size} selected</span>
          <button type="button" class="sds-use__copy"
            disabled={selected.size === 0}
            onClick={copySelection}>
            {status === 'copied' ? 'Copied' : status === 'failed' ? 'Copy failed' : 'Copy selection'}
          </button>
        </div>

        {/* The two things a prettier page would quietly leave out. */}
        <dl class="sds-use__gaps">
          <div>
            <dt>{data.totals.dynamicSites}</dt>
            <dd>sites pass props as expressions — counted, not rendered, because a guessed
              specimen is worse than an admitted gap.</dd>
          </div>
          <div>
            <dt>{data.totals.legacyButtons}</dt>
            <dd>legacy <code>&lt;button class="btn…"&gt;</code> across {data.totals.legacyFiles} files
              — still the larger population. This is the migration debt, not a rounding error.</dd>
          </div>
        </dl>
      </div>
    </section>
  );
}
