import type { Design } from '@payslip/types';

/** Generate a paste-ready TypeScript template file from a design. */
export function generateTemplateCode(design: Design, fnName = 'customTemplate'): string {
  const json = JSON.stringify(design, null, 2);
  return `import type { Design } from '@payslip/types';

/**
 * Generated by Payslip Studio.
 * Drop this file in src/templates/ and register it in src/templates/index.ts:
 *   import { ${fnName} } from './${fnName}';
 *   TEMPLATES = [..., { id: '${fnName}', label: '${fnName}', build: ${fnName} }]
 */
export function ${fnName}(): Design {
  return ${json} as Design;
}
`;
}

/** "SIOMAC Ltd." -> "siomacLtd" for a safe function name. */
export function toFnName(name: string): string {
  const cleaned = name.replace(/[^a-zA-Z0-9]+/g, ' ').trim().split(' ');
  const camel = cleaned
    .map((w, i) => (i === 0 ? w.toLowerCase() : w.charAt(0).toUpperCase() + w.slice(1).toLowerCase()))
    .join('');
  return /^[a-z]/.test(camel) ? camel : `t${camel}` || 'customTemplate';
}
