-- ============================================================================
-- Central Workflow Engine — role_permissions seed (Spec §22)
-- ============================================================================
-- Mirrors the code catalogue. employee = my tasks + decide-when-assigned;
-- manager = approvals + instance management; admin = full except admin_override;
-- superadmin = full. Idempotent. Run manually, then NOTIFY pgrst.
-- ============================================================================

insert into public.role_permissions (role_name, permission) values
  ('employee','workflow.my_tasks.view'),
  ('employee','workflow.tasks.approve'),
  ('employee','workflow.tasks.return'),
  ('employee','workflow.tasks.reject'),
  ('manager','workflow.dashboard.view'),
  ('manager','workflow.my_tasks.view'),
  ('manager','workflow.register.view'),
  ('manager','workflow.tasks.approve'),
  ('manager','workflow.tasks.return'),
  ('manager','workflow.tasks.reject'),
  ('manager','workflow.tasks.delegate'),
  ('manager','workflow.instances.view'),
  ('manager','workflow.instances.reassign'),
  ('manager','workflow.instances.escalate'),
  ('manager','workflow.instances.cancel'),
  ('manager','workflow.handoffs.view'),
  ('manager','workflow.audit.view'),
  ('admin','workflow.dashboard.view'),
  ('admin','workflow.my_tasks.view'),
  ('admin','workflow.register.view'),
  ('admin','workflow.tasks.approve'),
  ('admin','workflow.tasks.return'),
  ('admin','workflow.tasks.reject'),
  ('admin','workflow.tasks.delegate'),
  ('admin','workflow.instances.view'),
  ('admin','workflow.instances.reassign'),
  ('admin','workflow.instances.escalate'),
  ('admin','workflow.instances.cancel'),
  ('admin','workflow.instances.migrate'),
  ('admin','workflow.templates.view'),
  ('admin','workflow.templates.create'),
  ('admin','workflow.templates.update'),
  ('admin','workflow.templates.publish'),
  ('admin','workflow.templates.clone'),
  ('admin','workflow.templates.deprecate'),
  ('admin','workflow.bindings.view'),
  ('admin','workflow.bindings.create'),
  ('admin','workflow.bindings.update'),
  ('admin','workflow.bindings.activate'),
  ('admin','workflow.bindings.deactivate'),
  ('admin','workflow.handoffs.view'),
  ('admin','workflow.handoffs.retry'),
  ('admin','workflow.handoffs.cancel'),
  ('admin','workflow.audit.view'),
  ('admin','workflow.audit.export'),
  ('superadmin','workflow.dashboard.view'),
  ('superadmin','workflow.my_tasks.view'),
  ('superadmin','workflow.register.view'),
  ('superadmin','workflow.tasks.approve'),
  ('superadmin','workflow.tasks.return'),
  ('superadmin','workflow.tasks.reject'),
  ('superadmin','workflow.tasks.delegate'),
  ('superadmin','workflow.instances.view'),
  ('superadmin','workflow.instances.reassign'),
  ('superadmin','workflow.instances.escalate'),
  ('superadmin','workflow.instances.cancel'),
  ('superadmin','workflow.instances.admin_override'),
  ('superadmin','workflow.instances.migrate'),
  ('superadmin','workflow.templates.view'),
  ('superadmin','workflow.templates.create'),
  ('superadmin','workflow.templates.update'),
  ('superadmin','workflow.templates.publish'),
  ('superadmin','workflow.templates.clone'),
  ('superadmin','workflow.templates.deprecate'),
  ('superadmin','workflow.bindings.view'),
  ('superadmin','workflow.bindings.create'),
  ('superadmin','workflow.bindings.update'),
  ('superadmin','workflow.bindings.activate'),
  ('superadmin','workflow.bindings.deactivate'),
  ('superadmin','workflow.handoffs.view'),
  ('superadmin','workflow.handoffs.retry'),
  ('superadmin','workflow.handoffs.cancel'),
  ('superadmin','workflow.audit.view'),
  ('superadmin','workflow.audit.export')
on conflict do nothing;
