-- ============================================================================
-- HR Leave & Absence — settings (no-op migration)
-- ============================================================================
-- INTENTIONALLY EMPTY. HR Leave settings are declared in the settings MANIFEST
-- (netlify/functions/lib/settings/manifests/hrLeave.manifest.ts, registered in
-- manifests/index.ts) and seeded into the catalog by seedSettingsFromManifests()
-- — exactly like every other module (onboarding, employees, …). resolveSettingValue()
-- falls back to each setting's manifest defaultValue until the catalog is synced, so
-- the module is fully functional without any manual catalog rows.
--
-- The original hand-written INSERT here targeted a non-existent `settings_catalog`
-- table (the real table is `app_setting_catalog`) and duplicated the manifest — both
-- band-aids. Removed. Nothing to apply.
-- ============================================================================

-- (no-op)
